const dataList = [{
		id: 1,
		avada_img: "/static/hudong/c3.jpg",
		name: '李昊天',
		guanxi: '相互关注',
		time: '36',
		status: true,
		ta_take: '主要都是空气很好平路，欢迎喜欢行山的朋友加入。',
		detail_time: '2020年10月17日 18:00',
		number_ren: '9',
		dcse: '深圳天长地久高级心居 · 天心茶馆...',
		hd_img: '/static/hudong/s1.jpg',
		zhuti: '散步',
		old_time: '1天10小时37分',
		see: '98000',
		see_status: 0,
	},
	{
		id: 2,
		avada_img: '/static/hudong/c2.jpg',
		name: '琳姐',
		guanxi: '亲人',
		time: '52',
		watch: '1',
		status: false,
		ta_take: '主要都是空气很好平路入。',
		detail_time: '2020年05月17日 18:00',
		number_ren: '20',
		dcse: '深圳天长地久高级心居 · 深圳欢乐海岸城2号公馆',
		hd_img: '/static/hudong/s2.jpg',
		zhuti: '聚餐',
		old_time: '1天10小时37分',
		see: '1120',
		see_status: 0,
	},
	{
		id: 3,
		avada_img: '/static/hudong/c1.jpg',
		name: '赵小北',
		guanxi: '相互关注',
		time: '59',
		watch: '1',
		status: true,
		ta_take: '欢迎加入本次娱乐活动，感谢大家',
		detail_time: '2020年10月17日 18:00',
		number_ren: '9',
		dcse: '深圳天长地久高级心居 · 天心茶馆...',
		hd_img: '/static/hudong/s3.jpg',
		zhuti: '观花',
		old_time: '1天10小时37分',
		see: '112',
		see_status: 0,
	},
	{
		id: 4,
		avada_img: '/static/hudong/c4.jpg',
		name: '林佳音',
		guanxi: '朋友',
		time: '30',
		watch: '1',
		status: false,
		ta_take: '主要都是空气很好平路，欢迎喜欢行山的朋友加入。',
		detail_time: '2020年10月17日 18:00',
		number_ren: '9',
		dcse: '深圳天长地久高级心居 · 天心茶馆...',
		hd_img: '/static/hudong/s4.jpg',
		zhuti: '京剧',
		old_time: '1天10小时37分',
		see: '999',
		see_status: 0,
	}
]

const dataGuanzhu = [{
		id: 1,
		avada_img: "/static/hudong/c3.jpg",
		name: '李昊天',
		guanxi: '相互关注',
		guanxi_status:1,
		time: '36',
		status: true,
		ta_take: '主要都是空气很好平路，欢迎喜欢行山的朋友加入。',
		detail_time: '2020年10月17日 18:00',
		number_ren: '9',
		dcse: '深圳天长地久高级心居 · 天心茶馆...',
		hd_img: '/static/hudong/s1.jpg',
		zhuti: '散步',
		old_time: '1天10小时37分',
		see: '98000',
		see_status: 0
	},
	{
		id: 2,
		avada_img: '/static/hudong/c2.jpg',
		name: '琳姐',
		guanxi: '亲人',
		guanxi_status:1,
		time: '52',
		watch: '1',
		status: false,
		ta_take: '主要都是空气很好平路入。',
		detail_time: '2020年05月17日 18:00',
		number_ren: '20',
		dcse: '深圳天长地久高级心居 · 深圳欢乐海岸城2号公馆',
		hd_img: '/static/hudong/s2.jpg',
		zhuti: '聚餐',
		old_time: '1天10小时37分',
		see: '1120',
		see_status: 0,
	},
	{
		id: 3,
		avada_img: '/static/hudong/c1.jpg',
		name: '赵小北',
		guanxi: '相互关注',
		guanxi_status:1,
		time: '59',
		watch: '1',
		status: true,
		ta_take: '欢迎加入本次娱乐活动，感谢大家',
		detail_time: '2020年10月17日 18:00',
		number_ren: '9',
		dcse: '深圳天长地久高级心居 · 天心茶馆...',
		hd_img: '/static/hudong/s3.jpg',
		zhuti: '观花',
		old_time: '1天10小时37分',
		see: '112',
		see_status: 0
	},
	{
		id: 4,
		avada_img: '/static/hudong/c4.jpg',
		name: '林佳音',
		guanxi: '朋友',
		guanxi_status:1,
		time: '30',
		watch: '1',
		status: false,
		ta_take: '主要都是空气很好平路，欢迎喜欢行山的朋友加入。',
		detail_time: '2020年10月17日 18:00',
		number_ren: '9',
		dcse: '深圳天长地久高级心居 · 天心茶馆...',
		hd_img: '/static/hudong/s4.jpg',
		zhuti: '京剧',
		old_time: '1天10小时37分',
		see: '999',
		see_status: 0
	}
]

const fabuList = [{
		id: 1,
		avada_img: '/static/hudong/c3.jpg',
		name: '深圳天长地久高级心居',
		time: '36',
		see: '98000',
		dcse: '深圳优居社区准备筹备《元宵佳节》，时间1月24日，具体看活动详情',
		list_img: ['/static/hudong/s1.jpg', '/static/hudong/s2.jpg', '/static/hudong/s3.jpg'],
		fabuz: '深圳天长地久高级心居',
		old_time: '1天10小时37分'
	},
	{
		id: 2,
		avada_img: '/static/hudong/c2.jpg',
		name: '广州周希希高级心居',
		time: '78',
		see: '68000',
		dcse: '深圳优居社区准备筹备《元宵佳节》，时间1月24日，具体看活动详情',
		list_img: ['/static/hudong/s1.jpg', '/static/hudong/s2.jpg', '/static/hudong/s3.jpg',
			'/static/hudong/s4.jpg'
		],
		fabuz: '深圳天长地久高级心居',
		old_time: '1天10小时37分'
	}
]
const dataDaV = [{
		id: 1,
		avada_img: "/static/hudong/c3.jpg",
		name: '李昊天',
		guanxi: '相互关注',
		guanxi_status:0,
		time: '36',
		status: true,
		ta_take: '主要都是空气很好平路，欢迎喜欢行山的朋友加入。',
		detail_time: '2020年10月17日 18:00',
		number_ren: '9',
		dcse: '深圳天长地久高级心居 · 天心茶馆...',
		hd_img: '/static/hudong/s1.jpg',
		zhuti: '散步',
		old_time: '1天10小时37分',
		see: '98000',
		see_status: 1
	},
	{
		id: 2,
		avada_img: '/static/hudong/c2.jpg',
		name: '琳姐',
		guanxi: '亲人',
		guanxi_status:0,
		time: '52',
		watch: '1',
		status: false,
		ta_take: '主要都是空气很好平路入。',
		detail_time: '2020年05月17日 18:00',
		number_ren: '20',
		dcse: '深圳天长地久高级心居 · 深圳欢乐海岸城2号公馆',
		hd_img: '/static/hudong/s2.jpg',
		zhuti: '聚餐',
		old_time: '1天10小时37分',
		see: '1120',
		see_status: 1,
	},
	{
		id: 3,
		avada_img: '/static/hudong/c1.jpg',
		name: '赵小北',
		guanxi: '相互关注',
		guanxi_status:0,
		time: '59',
		watch: '1',
		status: true,
		ta_take: '欢迎加入本次娱乐活动，感谢大家',
		detail_time: '2020年10月17日 18:00',
		number_ren: '9',
		dcse: '深圳天长地久高级心居 · 天心茶馆...',
		hd_img: '/static/hudong/s3.jpg',
		zhuti: '观花',
		old_time: '1天10小时37分',
		see: '112',
		see_status: 1
	},
	{
		id: 4,
		avada_img: '/static/hudong/c4.jpg',
		name: '林佳音',
		guanxi: '朋友',
		guanxi_status:0,
		time: '30',
		watch: '1',
		status: false,
		ta_take: '主要都是空气很好平路，欢迎喜欢行山的朋友加入。',
		detail_time: '2020年10月17日 18:00',
		number_ren: '9',
		dcse: '深圳天长地久高级心居 · 天心茶馆...',
		hd_img: '/static/hudong/s4.jpg',
		zhuti: '京剧',
		old_time: '1天10小时37分',
		see: '999',
		see_status: 1
	}
]

// 优居人员列表数据
const userList = [
	{
		id: 1,
		avada_img: "/static/hudong/c3.jpg",
		name: '用户的昵称七个字',
		guanxi_status:1,
		qian_status: 1,
	},
	{
		id: 2,
		avada_img: "/static/hudong/c1.jpg",
		name: '李昊天',
		guanxi_status:1,
		qian_status: 1,
	},
	{
		id: 3,
		avada_img: "/static/hudong/c2.jpg",
		name: '李昊天',
		guanxi_status:0,
		qian_status: 1,
	},
	{
		id: 4,
		avada_img: "/static/hudong/c4.jpg",
		name: '李哲宇',
		guanxi_status:0,
		qian_status: 0,
	},
	{
		id: 5,
		avada_img: "/static/hudong/c3.jpg",
		name: '谈得来',
		guanxi_status:0,
		qian_status: 0,
	},
]

// 我的互动数据
const hudongData = [{
		id: 1,
		avada_img: "/static/hudong/c3.jpg",
		name: '李昊天',
		guanxi: '等确认',
		guanxi_status:0,
		time: '36',
		status: true,
		ta_take: '活着心态要好，主要都是空气很好平路，欢迎喜欢行山的朋友加入。',
		ruzhu:"深圳天长地久优居",
		call_time:"2020-03-18 19:27:49",
		hudong_number:"kj6644",
		dcse: '深圳天长地久高级心居 · 天心茶馆...',
		hd_img: '/static/hudong/s1.jpg',
		zhuti: '散步',
		old_time: '2020年03月30日 19:30',
		see: '98000',
		see_status: 1,
		texts_likai:'',
		texts_stutsa:"签到",
		text_address:"深圳仙湖植物园"
	},
	{
		id: 2,
		avada_img: '/static/hudong/c2.jpg',
		name: '琳姐',
		guanxi: '报名待确认',
		guanxi_status:0,
		time: '52',
		watch: '1',
		status: false,
		ta_take: '主要都是空气很好平路，欢迎喜欢行山的朋友加入。',
		ruzhu:"深圳天长地久优居",
		call_time:"2020-03-18 19:27:49",
		hudong_number:"kj66694",
		dcse: '深圳天长地久高级心居 · 深圳欢乐海岸城2号公馆',
		hd_img: '/static/hudong/s2.jpg',
		zhuti: '聚餐',
		old_time: '2020年04月02日 12:30',
		see: '1120',
		see_status: 1,
		texts_likai:"离开队伍",
		texts_stutsa:"取消报名",
		text_address:"佛山顺德东湖公园"
	},
	{
		id: 3,
		avada_img: '/static/hudong/c1.jpg',
		name: '赵小北',
		guanxi: '已开始',
		guanxi_status:0,
		time: '59',
		watch: '1',
		status: true,
		ta_take: '环境优美，欢迎各位的加入。',
		ruzhu:"长沙斯丹尼优居",
		call_time:"2020-03-18 19:27:49",
		hudong_number:"kj6644",
		dcse: '深圳天长地久高级心居 · 天心茶馆...',
		hd_img: '/static/hudong/s3.jpg',
		zhuti: '观花',
		old_time: '2020年04月15日 08:30',
		see: '112',
		see_status: 1,
		texts_likai:'',
		texts_stutsa:"签到",
		text_address:"深圳世界之窗"
	},
	{
		id: 4,
		avada_img: '/static/hudong/c4.jpg',
		name: '林佳音',
		guanxi: '已结束',
		guanxi_status:0,
		time: '30',
		watch: '1',
		status: false,
		ta_take: '主要都是空气很好平路，欢迎喜欢行山的朋友加入。大概的了解过了',
		ruzhu:"南山幅宽优居",
		call_time:"2020-08-18 19:27:49",
		hudong_number:"kj66333",
		dcse: '深圳天长地久高级心居 · 天心茶馆...',
		hd_img: '/static/hudong/s4.jpg',
		zhuti: '京剧',
		old_time: '2020年05月20日 15:20',
		see: '999',
		see_status: 1,
		texts_likai:'',
		texts_stutsa:"删除",
		text_address:"平峦山公园东北门"
	}
]

export default {
	dataList,
	fabuList,
	dataGuanzhu,
	dataDaV,
	userList,
	hudongData
}
